global using AngleSharp.Dom;
global using AngleSharp.Html.Parser;
global using DocumentFormat.OpenXml;
global using DocumentFormat.OpenXml.Packaging;
global using DocumentFormat.OpenXml.Wordprocessing;
global using SpreadsheetCell = DocumentFormat.OpenXml.Spreadsheet.Cell;
global using SpreadsheetRun = DocumentFormat.OpenXml.Spreadsheet.Run;
global using SpreadsheetRunProperties = DocumentFormat.OpenXml.Spreadsheet.RunProperties;
global using SpreadsheetBold = DocumentFormat.OpenXml.Spreadsheet.Bold;
global using SpreadsheetItalic = DocumentFormat.OpenXml.Spreadsheet.Italic;
global using SpreadsheetUnderline = DocumentFormat.OpenXml.Spreadsheet.Underline;
global using SpreadsheetStrike = DocumentFormat.OpenXml.Spreadsheet.Strike;
global using SpreadsheetColor = DocumentFormat.OpenXml.Spreadsheet.Color;
global using SpreadsheetFontSize = DocumentFormat.OpenXml.Spreadsheet.FontSize;
global using SpreadsheetRunFont = DocumentFormat.OpenXml.Spreadsheet.RunFont;
global using SpreadsheetText = DocumentFormat.OpenXml.Spreadsheet.Text;
global using SpreadsheetInlineString = DocumentFormat.OpenXml.Spreadsheet.InlineString;
