global using DocumentFormat.OpenXml;
global using DocumentFormat.OpenXml.Packaging;
global using DocumentFormat.OpenXml.Spreadsheet;
global using DocumentFormat.OpenXml.Wordprocessing;
global using OpenXmlHtml;
global using SpreadsheetCell = DocumentFormat.OpenXml.Spreadsheet.Cell;
global using SpreadsheetColor = DocumentFormat.OpenXml.Spreadsheet.Color;
global using SpreadsheetRun = DocumentFormat.OpenXml.Spreadsheet.Run;
global using SpreadsheetBold = DocumentFormat.OpenXml.Spreadsheet.Bold;
global using SpreadsheetItalic = DocumentFormat.OpenXml.Spreadsheet.Italic;
global using SpreadsheetStrike = DocumentFormat.OpenXml.Spreadsheet.Strike;
global using SpreadsheetUnderline = DocumentFormat.OpenXml.Spreadsheet.Underline;
global using SpreadsheetFontSize = DocumentFormat.OpenXml.Spreadsheet.FontSize;
global using SpreadsheetRunFont = DocumentFormat.OpenXml.Spreadsheet.RunFont;
global using SpreadsheetRunProperties = DocumentFormat.OpenXml.Spreadsheet.RunProperties;
global using SpreadsheetText = DocumentFormat.OpenXml.Spreadsheet.Text;
global using SpreadsheetInlineString = DocumentFormat.OpenXml.Spreadsheet.InlineString;
global using WBold = DocumentFormat.OpenXml.Wordprocessing.Bold;
global using WItalic = DocumentFormat.OpenXml.Wordprocessing.Italic;
global using WStrike = DocumentFormat.OpenXml.Wordprocessing.Strike;
global using WUnderline = DocumentFormat.OpenXml.Wordprocessing.Underline;
global using WColor = DocumentFormat.OpenXml.Wordprocessing.Color;
global using WFontSize = DocumentFormat.OpenXml.Wordprocessing.FontSize;
global using WRunProperties = DocumentFormat.OpenXml.Wordprocessing.RunProperties;
global using WRun = DocumentFormat.OpenXml.Wordprocessing.Run;
